import SwiftUI

/// Main content view — scaffolded by Axolotl.
/// The LLM agent will modify this view when generating the app.
struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundStyle(.tint)
            Text("Generated by Axolotl")
                .padding()
        }
        .padding()
    }
}

#Preview {
    ContentView()
}
