package com.agent.orchestrator.service;

import com.agent.orchestrator.model.Edge;
import com.agent.orchestrator.model.Node;
import com.agent.orchestrator.model.WorkflowSchema;
import com.agent.orchestrator.graph.repository.Neo4jSchemaRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.*;

@Service
public class SchemaExporter {

    private static final Logger log = LoggerFactory.getLogger(SchemaExporter.class);

    private final Neo4jSchemaRepository schemaRepository;

    public SchemaExporter(Neo4jSchemaRepository schemaRepository) {
        this.schemaRepository = schemaRepository;
    }

    public String exportToMermaid(String id) {
        WorkflowSchema schema = schemaRepository.findById(id);
        if (schema == null)
            return "";

        StringBuilder mermaid = new StringBuilder();
        mermaid.append("```mermaid\ngraph TD\n");

        if (schema.getNodes() != null) {
            for (Node node : schema.getNodes()) {
                String shape = getNodeShape(node.getType());
                String label = node.getName().replace("\"", "\\\"");
                mermaid.append(String.format("    %s%s[\"%s\"]%n", node.getId(), shape, label));
            }
        }

        if (schema.getEdges() != null) {
            for (Edge edge : schema.getEdges()) {
                String edgeStyle = getEdgeStyle(edge.getType());
                mermaid.append(String.format("    %s %s %s%n", edge.getSource(), edgeStyle, edge.getTarget()));
            }
        }

        mermaid.append("```");
        return mermaid.toString();
    }

    public String exportToPython(String id) {
        WorkflowSchema schema = schemaRepository.findById(id);
        if (schema == null) return "";

        StringBuilder py = new StringBuilder();
        py.append("#!/usr/bin/env python3\n");
        py.append("# Axolotl Schema: ").append(schema.getName()).append("\n");
        py.append("# Generated by Axolotl\n\n");
        py.append("import requests\n");
        py.append("import json\n");
        py.append("import sys\n");
        py.append("from typing import Dict, Any, List\n\n");

        // Build execution levels (topological sort)
        List<List<Node>> levels = computeExecutionLevels(schema);

        // Variables to hold results
        py.append("# Results storage\n");
        py.append("results: Dict[str, str] = {}\n\n");

        // Helper functions
        py.append("def call_ollama(prompt: str, system_prompt: str = \"\", model: str = \"gemma4:e2b\") -> str:\n");
        py.append("    \"\"\"Call Ollama LLM\"\"\"\n");
        py.append("    url = \"http://localhost:11434/api/chat\"\n");
        py.append("    messages = []\n");
        py.append("    if system_prompt:\n");
        py.append("        messages.append({\"role\": \"system\", \"content\": system_prompt})\n");
        py.append("    messages.append({\"role\": \"user\", \"content\": prompt})\n");
        py.append("    resp = requests.post(url, json={\"model\": model, \"messages\": messages, \"stream\": False})\n");
        py.append("    resp.raise_for_status()\n");
        py.append("    return resp.json()[\"message\"][\"content\"]\n\n");

        py.append("def interpolate(text: str, results: Dict[str, str]) -> str:\n");
        py.append("    \"\"\"Replace {{variable}} placeholders\"\"\"\n");
        py.append("    import re\n");
        py.append("    def replacer(m):\n");
        py.append("        key = m.group(1).strip()\n");
        py.append("        return results.get(key, m.group(0))\n");
        py.append("    return re.sub(r'\\{\\{(.+?)\\}\\}', replacer, text)\n\n");

        // Generate code for each level
        for (int i = 0; i < levels.size(); i++) {
            py.append("# === Level ").append(i).append(" (parallel) ===\n");
            for (Node node : levels.get(i)) {
                generatePythonForNode(py, node, schema);
                py.append("\n");
            }
        }

        // Final output
        py.append("\n# === Print final results ===\n");
        py.append("print(\"\\n--- Execution Complete ---\")\n");
        py.append("for name, result in results.items():\n");
        py.append("    print(f\"{name}: {result[:200]}\")\n");

        return py.toString();
    }

    public List<List<Node>> computeExecutionLevels(WorkflowSchema schema) {
        List<List<Node>> levels = new ArrayList<>();
        if (schema.getNodes() == null || schema.getNodes().isEmpty()) return levels;

        Map<String, Integer> inDegree = new HashMap<>();
        Map<String, List<String>> adj = new HashMap<>();
        for (Node n : schema.getNodes()) {
            inDegree.put(n.getId(), 0);
            adj.put(n.getId(), new ArrayList<>());
        }
        if (schema.getEdges() != null) {
            for (Edge e : schema.getEdges()) {
                adj.get(e.getSource()).add(e.getTarget());
                inDegree.merge(e.getTarget(), 1, Integer::sum);
            }
        }

        List<String> queue = new ArrayList<>();
        for (var entry : inDegree.entrySet()) {
            if (entry.getValue() == 0) queue.add(entry.getKey());
        }

        Map<String, Node> nodeMap = new HashMap<>();
        for (Node n : schema.getNodes()) nodeMap.put(n.getId(), n);

        while (!queue.isEmpty()) {
            List<Node> level = new ArrayList<>();
            for (String nodeId : queue) level.add(nodeMap.get(nodeId));
            levels.add(level);

            List<String> nextQueue = new ArrayList<>();
            for (String nodeId : queue) {
                for (String neighbor : adj.get(nodeId)) {
                    int newDeg = inDegree.merge(neighbor, -1, Integer::sum);
                    if (newDeg == 0) nextQueue.add(neighbor);
                }
            }
            queue = nextQueue;
        }

        return levels;
    }

    public void generatePythonForNode(StringBuilder py, Node node, WorkflowSchema schema) {
        String varName = node.getName().replaceAll("[^a-zA-Z0-9_]", "_");

        switch (node.getType()) {
            case "source":
                String sourceData = node.getData() != null && node.getData().getSourceData() != null
                        ? escapePythonString(node.getData().getSourceData()) : "";
                py.append("results[\"").append(varName).append("\"] = \"").append(sourceData).append("\"\n");
                break;

            case "agent":
                String userPrompt = node.getData() != null && node.getData().getUserPrompt() != null
                        ? escapePythonString(node.getData().getUserPrompt()) : "";
                String systemPrompt = node.getData() != null && node.getData().getSystemPrompt() != null
                        ? escapePythonString(node.getData().getSystemPrompt()) : "";
                String model = node.getData() != null && node.getData().getModel() != null
                        ? escapePythonString(node.getData().getModel()) : "gemma4:e2b";

                py.append("# Agent: ").append(node.getName()).append("\n");
                py.append("print(\"Running agent: ").append(node.getName()).append("\")\n");
                py.append("prompt_").append(varName).append(" = interpolate(\"").append(userPrompt).append("\", results)\n");
                if (!systemPrompt.isEmpty()) {
                    py.append("system_").append(varName).append(" = interpolate(\"").append(systemPrompt).append("\", results)\n");
                }
                py.append("results[\"").append(varName).append("\"] = call_ollama(");
                py.append("prompt=prompt_").append(varName).append(", ");
                if (!systemPrompt.isEmpty()) {
                    py.append("system_prompt=system_").append(varName).append(", ");
                }
                py.append("model=\"").append(model).append("\")\n");
                break;

            case "condition":
                String condition = node.getData() != null && node.getData().getCondition() != null
                        ? node.getData().getCondition() : "true";
                py.append("# Condition: ").append(node.getName()).append("\n");
                py.append("results[\"").append(varName).append("\"] = str(").append(condition).append(")\n");
                break;

            case "output":
                py.append("# Output: ").append(node.getName()).append("\n");
                py.append("print(f\"Output: {results}\")\n");
                break;

            case "memory":
                String searchQuery = node.getData() != null && node.getData().getSourceData() != null
                        ? escapePythonString(node.getData().getSourceData()) : node.getName();
                py.append("# Memory search: ").append(node.getName()).append("\n");
                py.append("results[\"").append(varName).append("\"] = \"Memory search: ").append(searchQuery).append(" (stub)\"\n");
                break;

            default:
                py.append("# ").append(node.getType()).append(": ").append(node.getName()).append(" (not implemented in Python export)\n");
                py.append("results[\"").append(varName).append("\"] = \"\"\n");
                break;
        }
    }

    public String escapePythonString(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    public String getNodeShape(String type) {
        return switch (type) {
            case "agent" -> "";
            case "source" -> "[/";
            case "output" -> "[\\";
            case "condition" -> "{";
            default -> "[";
        };
    }

    public String getEdgeStyle(String type) {
        return switch (type) {
            case "control" -> "==>";
            case "condition" -> "-.->";
            default -> "-->";
        };
    }
}
